### ISSUE TITLE
Add command line options for runtime variables, with sensible defaults

### ISSUE THREAD

**Issue by vielmetti** [jpmens/1090-to-owntracks#2]
My dump1090 configuration is slightly different (I'm running [mutability/dump1090](https://github.com/mutability/dump1090)), and eventually I'll also be also feeding a private server in addition to the public server. I'd like to do this without needing to fork the script.

So, the proposal is to pull runtime variables from a configuration file or from the command line, specifically the following ones:
- url in get_aircraft()
- mqttc.connect() variables including host, port, timeout
- topic, currently 'ot/flights/%s'

The current defaults are sensible, so it would be sensible that if you ran this with no options, it would do exactly what it's doing now. I'm thinking something like

```
1090-to-owntracks --url 'http://localhost/dump1090/data/aircraft.json' --mqtthost mqtt.example.org 
```

would do the right thing using a default port and timeout and the standard topic.

**Comment by jpmens** [comment]
Good idea; I'll accept a PR. 😄

**Comment by vielmetti** [comment]
PR submitted for argument parsing, didn't get as far as a config file just yet.
